spring:
    application:
        name: msapigateway
server:
    port: ${SERVER-PORT}
    contextPath: /  
eureka:
  instance:
    hostname: ${SERVER-HOST}
  client:
    preferSameZoneEureka: true
    registerWithEureka: true
    fetchRegistry: true
    region: ${REGION}
    preferSameZoneEureka: true 
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER1-HOST}:${EUREKA-SERVER1-PORT}/eureka/,http://${EUREKA-SERVER2-HOST}:${EUREKA-SERVER2-PORT}/eureka/ 
ribbon:
    eureka:
        enabled: true
        MaxAutoRetries: 0
        MaxAutoRetriesNextServer: 0
        ReadTimeout: 10000
