# to deploy the app on the cloud hosted swarm
# Open docker compose and see, it has services listed
# it runs on swarm created already
#docker stack deploy -c docker-compose-east.yml ml_cloud_stack

#https://github.com/dockersamples/example-voting-app

# EACH LINE IN DOCKER COMPOSE is equaialent to arguments in docker run
# Why docker compose ??? To aggregate all docker runs, like a dockerrun.bat

version: '3.3'
services:
    eureka-east-server1:
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            - REGION=east
            - EUREKA-SERVER-HOST=0.0.0.0
            - EUREKA-SERVER-PORT=8761
            - EUREKA-PEER-SERVER-HOST=0.0.0.0
            - EUREKA-PEER-SERVER-PORT=8762
            - JAVA_OPTS=-Xms256m -Xmx512m
        expose:
            - 8761
        ports:
            - "8761:8761"
        networks:
            - ml-cloud-network-east
        volumes:
            - userdata:/var/www/mlservicedatadir
        logging:
            driver: json-file
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:8761"]
          interval: 120s
          timeout: 60s
          retries: 10          
        restart: on-failure                   
    eureka-east-server2:
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            - REGION=east
            - EUREKA-SERVER-HOST=0.0.0.0
            - EUREKA-SERVER-PORT=8762
            - EUREKA-PEER-SERVER-HOST=0.0.0.0
            - EUREKA-PEER-SERVER-PORT=8761
            - JAVA_OPTS=-Xms256m -Xmx512m
        expose:
            - 8762
        ports:
            - "8762:8762"
        networks:
            - ml-cloud-network-east
        volumes:
            - userdata:/var/www/mlservicedatadir
        logging:
            driver: json-file
#        depends_on:
#            - eureka-east-server1            
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:8762"]
          interval: 120s
          timeout: 60s
          retries: 10       
        restart: on-failure     
    msapigateway-east-server1:
        image: santhoshcheeran/msapigatewayrepo:latest
        environment:
            - SERVER-PORT=8091
            - SERVER-HOST=0.0.0.0
            - REGION=east
            - EUREKA-SERVER1-HOST=0.0.0.0
            - EUREKA-SERVER1-PORT=8761
            - EUREKA-SERVER2-HOST=0.0.0.0
            - EUREKA-SERVER2-PORT=8762       
            - JAVA_OPTS=-Xms256m -Xmx512m
        expose:
            - 8091
        ports:
            - "8091:8091"
        networks:
            - ml-cloud-network-east
        volumes:
            - userdata:/var/www/mlservicedatadir
        logging:
            driver: json-file
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:8091"]
          interval: 120s
          timeout: 60s
          retries: 10             
        restart: on-failure       
    zipkinserver-east-server1:
        image: santhoshcheeran/zipkinserverrepo:latest
        environment:
            - SERVER-PORT=9411
            - SERVER-HOST=0.0.0.0
            - REGION=east
            - EUREKA-SERVER1-HOST=0.0.0.0
            - EUREKA-SERVER1-PORT=8761
            - EUREKA-SERVER2-HOST=0.0.0.0
            - EUREKA-SERVER2-PORT=8762
            - JAVA_OPTS=-Xms256m -Xmx512m
        expose:
            - 9411
        ports:
            - "9411:9411"
        networks:
            - ml-cloud-network-east
        volumes:
            - userdata:/var/www/mlservicedatadir
        logging:
            driver: json-file
        healthcheck:
          test: ["CMD", "curl", "-f", "http://0.0.0.0:9411"]
          interval: 120s
          timeout: 60s
          retries: 10           
        restart: on-failure        
networks:
    ml-cloud-network-east:
        external: true
volumes:
    userdata:
        external: true
