# to deploy the app on the cloud hosted swarm
# Open docker compose and see, it has services listed
# it runs on swarm created already
#docker stack deploy -c docker-compose-east.yml ml_cloud_stack

# EACH LINE IN DOCKER COMPOSE is equaialent to arguments in docker run
# Why docker compose ??? To aggregate all docker runs, like a dockerrun.bat

version: '1'
services:
    eureka-west-server1:
        container_name: eureka-west-server1
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            REGION=West
            EUREKA-SERVER-HOST=localhost
            EUREKA-SERVER-PORT=8763
            EUREKA-PEER-SERVER-HOST=localhost
            EUREKA-PEER-SERVER-PORT=8764
        expose:
            - 8763
            - 8764
        ports:
            - "8763:8763"
            - "8764:8764"
        networks:
            - ml-cloud-network-east
        volumes:
            - mlservicedatadir:/var/www/mlservicedatadir
        logging:
            driver: json-file
        links:
            mlservice,msapigateway,zipkinserver
networks:
    ml-cloud-network-east:
        driver: bridge
volumes:
    mlservicedatadir:
        external: true

santhoshcheeran/mlservicerepo
santhoshcheeran/msapigatewayrepo
santhoshcheeran/zipkinserverrepo
