version: '2.2'
services:
    eureka-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server1
        healthcheck:
          test: "exit 0"
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M        
    eureka-east-server2:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server2
        healthcheck:
          test: "exit 0"
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M                
        depends_on:
            - eureka-east-server1
    msapigateway-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: msapigateway-east-server1
        healthcheck:
          test: "exit 0"
        restart: always   
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M             
        depends_on:
            - mlserver-east
    zipkinserver-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: zipkinserver-east-server1
        healthcheck:
          test: "exit 0"
        restart: always  
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M                
    mlserver-east:
        extends:
            file: docker-compose-east.yml
            service: mlserver-east
        healthcheck:
          test: "exit 0"
        restart: always      
        deploy:
          resources:
            limits:
              cpus: '0.01'
              memory: 250M
            reservations:
              cpus: '0.01'
              memory: 50M                
        depends_on:
            - eureka-east-server2
            - zipkinserver-east-server1   
