version: '2.2'
services:
    eureka-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8761"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M        
    eureka-east-server2:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server2
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8762"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always     
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M                
        depends_on:
            - eureka-east-server1
    msapigateway-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: msapigateway-east-server1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8091"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always                 
        depends_on:
            - mlserver-east
    zipkinserver-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: zipkinserver-east-server1
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9411"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always    
        deploy:
          resources:
            limits:
              cpus: '0.001'
              memory: 50M
            reservations:
              cpus: '0.0001'
              memory: 20M                
    mlserver-east:
        extends:
            file: docker-compose-east.yml
            service: mlserver-east
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always        
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: 250M
            reservations:
              cpus: '0.1'
              memory: 50M                
        depends_on:
            - eureka-east-server2
            - zipkinserver-east-server1   
