version: '3.7'
services:	
    mlserver-west:	
        container_name: mlserver_west
        build:	
            context: .	
            dockerfile: DockerFile.mlservice	
        image: santhoshcheeran/mlservicerepo:latest	
        environment:	
            - ZUULPROXYADDRESS=http://localhost:8092	
            - SERVER-PORT=8081
            - SERVER-HOST=localhost
            - REGION=west
            - EUREKA-SERVER1-HOST=localhost
            - EUREKA-SERVER1-PORT=8763
            - EUREKA-SERVER2-HOST=localhost
            - EUREKA-SERVER2-PORT=8764
        expose:	
            - 8081
        # cannot use "8081:8081" - because the format will bind 8080 to 8080 and docker compose cannot use scale, as only one server can use this port
        # https://pspdfkit.com/blog/2018/how-to-use-docker-compose-to-run-multiple-instances-of-a-service-in-development/
        ports:
            - 8081
        networks:	
            - ml-cloud-network-west	
        volumes:	
            - mlservicedatadir:/var/www/mlservicedatadir	
        logging:	
            driver: json-file	
        deploy:	
            replicas: 2	
            update_config:	
                parallelism: 1	
                delay: 10s	
            restart_policy: 	
                condition: on-failure	
            placement:	
                constraints: [node.role == worker]	
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - mlserver-east
        ports:
            - "4000:4000"                
networks:	
    ml-cloud-network-west:	
        driver: bridge	
volumes:	
    mlservicedatadir:	
        external: true	
