services:	
    mlserver-west-server1:	
        container_name: mlservice_container	
        build:	
            context: .	
            dockerfile: DockerFile.mlservice	
        image: santhoshcheeran/mlservicerepo:latest	
        environment:	
            ZUULPROXYADDRESS=http://localhost:8092	
            SERVER-PORT=8080	
            SERVER-HOST=localhost	
            REGION=west	
            EUREKA-SERVER1-HOST=localhost	
            EUREKA-SERVER1-PORT=8763	
            EUREKA-SERVER2-HOST=localhost	
            EUREKA-SERVER2-PORT=8764           	
        expose:	
            - 8081	
        ports:	
            - "8081:8081"	
        networks:	
            - ml-cloud-network-west	
        volumes:	
            - mlservicedatadir:/var/www/mlservicedatadir	
        logging:	
            driver: json-file	
        links:	
            msapigateway,zipkinserver	
        deploy:	
            replicas: 2	
            update_config:	
                parallelism: 1	
                delay: 10s	
            restart_policy: 	
                condition: on-failure	
            placement:	
                constraints: [node.role == worker]	
networks:	
    ml-cloud-network-west:	
        driver: bridge	
volumes:	
    mlservicedatadir:	
        external: true	
