version: '2.2'
services:
    eureka-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server1
        healthcheck:
          test: "exit 0"
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.001'
            reservations:
              cpus: '0.0001'    
    eureka-east-server2:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server2
        healthcheck:
          test: "exit 0"
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.001'
            reservations:
              cpus: '0.0001'            
        depends_on:
            - eureka-east-server1:
                condition: service_healthy
            
    msapigateway-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: msapigateway-east-server1
        healthcheck:
          test: "exit 0"
        restart: always   
        deploy:
          resources:
            limits:
              cpus: '0.001'
            reservations:
              cpus: '0.0001'          
        depends_on:
            - mlserver-east:
                condition: service_healthy
    zipkinserver-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: zipkinserver-east-server1
        healthcheck:
          test: "exit 0"
        restart: always  
        deploy:
          resources:
            limits:
              cpus: '0.001'
            reservations:
              cpus: '0.0001'           
    mlserver-east:
        extends:
            file: docker-compose-east.yml
            service: mlserver-east
        healthcheck:
          test: "exit 0"
        restart: always      
        deploy:
          resources:
            limits:
              cpus: '0.01'
            reservations:
              cpus: '0.01'           
        depends_on:
            - eureka-east-server2:
                condition: service_healthy
            - zipkinserver-east-server1:
                condition: service_healthy   
