version: '3.3'
services:
  mlserver-east:
#    build:
#      context: .
#      dockerfile: MLService/docker/DockerFile.mlservice
    image: 'santhoshcheeran/mlservicerepo:latest'
    environment:
      - ZUULPROXYADDRESS=http://msapigateway-east-1:8091
      - SERVER-PORT=8080
      - SERVER-HOST=mlserver-east-1
      - REGION=east
      - EUREKA-SERVER1-HOST=eureka-east-1
      - EUREKA-SERVER1-PORT=8761
      - EUREKA-SERVER2-HOST=eureka-east-2
      - EUREKA-SERVER2-PORT=8762
      - JAVA_OPTS=-Xms128m -Xmx256m
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mlserver-east-1:8080/health"]
      interval: 120s
      timeout: 60s
      retries: 3  
    restart: on-failure
    networks:
        ml-cloud-network-east:
            aliases:
                - mlserver-east-1 
    volumes:
      - userdata:/var/www/mlservicedatadir
    logging:
      driver: json-file
  nginx:
    image: 'nginx:latest'
    networks:
        ml-cloud-network-e./NginxConf/nginx.confst:
            aliases:
                - nginx-east-1     
    #volumes:
    configs:
        source: 
            - ./NginxConf/nginx.conf
        target:
            - /etc/nginx/nginx.conf
    ports:
      - '80:8888'
networks:
    ml-cloud-network-east: 
        external: true
volumes:
    userdata:
        external: true
