version: '3.7'
services:
  mlserver-east:
    container_name: mlserver_east
#    build:
#      context: .
#      dockerfile: MLService/docker/DockerFile.mlservice
    image: 'santhoshcheeran/mlservicerepo:latest'
    environment:
      - 'ZUULPROXYADDRESS="http://localhost:8091"'
      - SERVER-PORT=8080
      - SERVER-HOST=localhost
      - REGION=East
      - EUREKA-SERVER1-HOST=localhost
      - EUREKA-SERVER1-PORT=8761
      - EUREKA-SERVER2-HOST=localhost
      - EUREKA-SERVER2-PORT=8762
    expose:
      - 8080
    ports:
      - 8080
    depends_on:
      - nginx
    networks:
      - ml-cloud-network-east
    volumes:
      - userdata:/var/www/mlservicedatadir
    logging:
      driver: json-file
# docker swarm ???
#    deploy:
#      replicas: 2
#      update_config:
#        parallelism: 1
#        delay: 10s
#      restart_policy:
#            condition: on-failure
#      placement:
#        constraints:
#          - 'node.role == worker'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
networks:
    ml-cloud-network-east: 
        external: true
volumes:
    userdata:
        external: true
