version: '2.2'
services:
    eureka-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server1
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8761"]
        restart: always
#        deploy:
#          resources:
#            limits:
#              cpus: '0.001'
#            reservations:
#              cpus: '0.0001'    
    eureka-east-server2:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server2
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8762"]
        restart: always
#        deploy:
#          resources:
#            limits:
#              cpus: '0.001'
#            reservations:
#              cpus: '0.0001'              
        depends_on:
            - eureka-east-server1          
    msapigateway-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: msapigateway-east-server1
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8091"]
        restart: always   
#        deploy:
#          resources:
#            limits:
#              cpus: '0.001'
#            reservations:
#              cpus: '0.0001'             
        depends_on:
            - mlserver-east
    zipkinserver-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: zipkinserver-east-server1
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9411"]
        restart: always  
#        deploy:
#          resources:
#            limits:
#              cpus: '0.001'
#            reservations:
#              cpus: '0.0001'            
    mlserver-east:
        extends:
            file: docker-compose-east.yml
            service: mlserver-east
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8091"]
        restart: always      
#        deploy:
#          resources:
#            limits:
#              cpus: '0.01'
#            reservations:
#              cpus: '0.001'              
        depends_on:
            - eureka-east-server2
            - zipkinserver-east-server1  
