# to deploy the app on the cloud hosted swarm
# Open docker compose and see, it has services listed
# it runs on swarm created already
#docker stack deploy -c docker-compose-east.yml ml_cloud_stack

#https://github.com/dockersamples/example-voting-app

# EACH LINE IN DOCKER COMPOSE is equaialent to arguments in docker run
# Why docker compose ??? To aggregate all docker runs, like a dockerrun.bat

version: '3.7'
services:
    eureka-east-server1:
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            - REGION=east
            - EUREKA-SERVER-HOST=localhost
            - EUREKA-SERVER-PORT=8761
            - EUREKA-PEER-SERVER-HOST=localhost
            - EUREKA-PEER-SERVER-PORT=8762
        expose:
            - 8761
        ports:
            - "8761:8761"
        networks:
            - ml-cloud-network-east
        volumes:
            - mlservicedatadir-east
        logging:
            driver: json-file
#        deploy:
#            replicas: 1
#            update_config:
#                parallelism: 1
#                delay: 10s
#            restart_policy: 
#                condition: on-failure
#            placement:
#                constraints: [node.role == worker]
    eureka-east-server2:
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            - REGION=east
            - EUREKA-SERVER-HOST=localhost
            - EUREKA-SERVER-PORT=8762
            - EUREKA-PEER-SERVER-HOST=localhost
            - EUREKA-PEER-SERVER-PORT=8761
        expose:
            - 8762
        ports:
            - "8762:8762"
        networks:
            - ml-cloud-network-east
        volumes:
            - mlservicedatadir-east
        logging:
            driver: json-file
#        deploy:
#            replicas: 1
#            update_config:
#                parallelism: 1
#                delay: 10s
#            restart_policy: 
#                condition: on-failure
#            placement:
#                constraints: [node.role == worker]
    msapigateway-east-server1:
        build:
            context: .
            dockerfile: DockerFile.msapigateway
        image: santhoshcheeran/msapigatewayrepo:latest
        environment:
            - SERVER-PORT=8091
            - SERVER-HOST=localhost
            - REGION=east
            - EUREKA-SERVER1-HOST=localhost
            - EUREKA-SERVER1-PORT=8761
            - EUREKA-SERVER2-HOST=localhost
            - EUREKA-SERVER2-PORT=8762       
        expose:
            - 8091
        ports:
            - "8091:8091"
        networks:
            - ml-cloud-network-east
        volumes:
            - mlservicedatadir-east
        logging:
            driver: json-file
        depends_on:
            - eureka-east-server1
            - eureka-east-server2
            - zipkinserver-east-server1
#        deploy:
#            replicas: 1
#            update_config:
#                parallelism: 1
#                delay: 10s
#            restart_policy: 
#                condition: on-failure
#            placement:
#                constraints: [node.role == worker]
    zipkinserver-east-server1:
        build:
            context: .
            dockerfile: DockerFile.zipkinserver
        image: santhoshcheeran/zipkinserverrepo:latest
        environment:
            - SERVER-PORT=9411
            - SERVER-HOST=localhost
            - REGION=east
            - EUREKA-SERVER1-HOST=localhost
            - EUREKA-SERVER1-PORT=8761
            - EUREKA-SERVER2-HOST=localhost
            - EUREKA-SERVER2-PORT=8762
        expose:
            - 9411
        ports:
            - "9411:9411"
        networks:
            - ml-cloud-network-east
        volumes:
            - mlservicedatadir-east
        logging:
            driver: json-file
#        deploy:
#            replicas: 1
#            update_config:
#                parallelism: 1
#                delay: 10s
#            restart_policy: 
#                condition: on-failure
#            placement:
#                constraints: [node.role == worker]
networks:
    ml-cloud-network-east:
        external: false
volumes:
    mlservicedatadir-east: /var/www/mlservicedatadir-east
        external: false          
