version: '3.7'
services:
    eureka-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server1
    eureka-east-server2:
        extends:
            file: docker-compose-east-framework.yml
            service: eureka-east-server2            
    msapigateway-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: msapigateway-east-server1        
    zipkinserver-east-server1:
        extends:
            file: docker-compose-east-framework.yml
            service: zipkinserver-east-server1   
    mlserver-east:
        extends:
            file: docker-compose-east.yml
            service: mlserver-east
