version: '1'
services:
    eureka-east-server1:
        container_name: eureka-east-server1
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            REGION=East
            EUREKA-SERVER-HOST=localhost
            EUREKA-SERVER-PORT=8761
            EUREKA-PEER-SERVER-HOST=localhost
            EUREKA-PEER-SERVER-PORT=8762
        expose:
            - 8761
            - 8762
        ports:
            - 8761:8761
            - 8762:8762
        networks:
            - ml-cloud-network
        volumes:
            - mlservicedatadir:/var/www/mlservicedatadir
        logging:
            driver: json-file
services:
    eureka-west-server1:
        container_name: eureka-west-server1
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mleurekaserverrepo:latest
        environment:
            REGION=West
            EUREKA-SERVER-HOST=localhost
            EUREKA-SERVER-PORT=8763
            EUREKA-PEER-SERVER-HOST=localhost
            EUREKA-PEER-SERVER-PORT=8764
        expose:
            - 8763
            - 8764
        ports:
            - 8763:8763
            - 8764:8764
        networks:
            - ml-cloud-network
        volumes:
            - mlservicedatadir:/var/www/mlservicedatadir
        logging:
            driver: json-file            
networks:
    ml-cloud-network:
        driver: bridge
volumes:
    mlservicedatadir:
        external: true
