version: '1'
services:
    eureka-east-server1:
        container_name: eurekaserver-instance-east1
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mlrepo:latest
        environment:
            REGION=East
            EUREKA-SERVER-HOST=localhost
            EUREKA-SERVER-PORT=8761 
            EUREKA-PEER-SERVER-HOST=localhost
            EUREKA-PEER-SERVER-PORT=8762		
        expose:
            - 8761
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
        volumes:
            - mlservicerootdir:/var/www/mlservicerootdir/
        logging:
            driver: json-file
services:
    eureka-east-server2:
        container_name: eureka-east-server2
        build:
            context: .
            dockerfile: DockerFile.eureka
        image: santhoshcheeran/mlrepo:latest
        environment:
            REGION=East
            EUREKA-SERVER-HOST=localhost
            EUREKA-SERVER-PORT=8762 
            EUREKA-PEER-SERVER-HOST=localhost
            EUREKA-PEER-SERVER-PORT=8761	
        expose:
            - 8762
        ports:
            - 8762:8762            
        networks:
            - spring-cloud-network
        volumes:
            - mlservicerootdir:/var/www/mlservicerootdir/
        logging:
            driver: json-file            
networks:
    spring-cloud-network:
        driver: bridge
volumes:
    mlservicerootdir:
        external: true
