#The server comes with a client config, but we do not want that to register
#The server starts itself at ureka  http://localhost:8761/eureka/   
#which is localhost:port
spring:
    application:
        name: zipkin
server:
    port: ${SERVER-PORT:9411}
    contextPath: /  
eureka:
    instance:
      hostname: ${SERVER-HOST:0.0.0.0}
    client:
        registerWithEureka: true
        fetchRegistry: true
        region: ${REGION:east}
        serviceUrl:
            defaultZone: http://${EUREKA-SERVER1-HOST:0.0.0.0}:${EUREKA-SERVER1-PORT:8761}/eureka,http://${EUREKA-SERVER2-HOST:0.0.0.0}:${EUREKA-SERVER2-PORT:8762}/eureka             
    server:
        waitTimeInMsWhenSyncEmpty: 0        
