spring:
    application:
        name: mls
eureka:
    client:
        registerWithEureka: true 
        fetchRegistry: true    
        healthcheck:
            enabled: true        
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/} 
    server:
        waitTimeInMsWhenSyncEmpty: 0
        port: 8080