#The server comes with a client config, but we do not want that to register
#The server starts itself at eureka  http://localhost:8761/eureka/   
#which is localhost:port
spring:
    application:
        name: mleurekaserver
server:
    port: ${SERVER-PORT}
    contextPath: /  
eureka:
    instance:
        hostname: ${EUREKA-SERVER-HOST}
    client:
        registerWithEureka: false
        fetchRegistry: false
        service-url:
            defaultZone: http://${PEER-SERVER-HOST}:${PEER-SERVER-PORT}/eureka/
