spring:
    application:
        name: MLService
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0
        port: 8080
        contextPath: MLService