spring:
    application:
        name: mls
server:
    port: ${SERVER-PORT}
    contextPath: /
eureka:
    instance:
        hostname: ${SERVER-HOST}
    client:
        registerWithEureka: true
        fetchRegistry: true
        region: ${REGION}
        preferSameZoneEureka: true 
        healthcheck:
            enabled: true        
        serviceUrl:
            defaultZone: http://${EUREKA-SERVER1-HOST}:${EUREKA-SERVER1-PORT}/eureka/,http://${EUREKA-SERVER2-HOST}:${EUREKA-SERVER2-PORT}/eureka/ 
    server:
        waitTimeInMsWhenSyncEmpty: 0
        port: 8080
