spring:
    application:
        name: mls
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true    
        healthcheck:
            enabled: true        
        serviceUrl:
            defaultZone: http://${EUREKA-SERVER1-HOST}:${EUREKA-SERVER1-PORT}/eureka/,http://${EUREKA-SERVER2-HOST}:${EUREKA-SERVER2-PORT}/eureka/ 
    server:
        waitTimeInMsWhenSyncEmpty: 0
        port: 8080
